//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaiKhatNgocMai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.ItemPhotoes = new HashSet<ItemPhoto>();
        }
    
        public int Id { get; set; }
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public int CategoryId { get; set; }
        public decimal Price { get; set; }
        public string Unit { get; set; }
        public bool IsFeatured { get; set; }
        public string Image { get; set; }
        public bool IsTopping { get; set; }
        public string UrlName { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<ItemPhoto> ItemPhotoes { get; set; }
    }
}
