//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaiKhatNgocMai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public OrderDetail()
        {
            this.OrderDetail1 = new HashSet<OrderDetail>();
        }
    
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int ItemId { get; set; }
        public Nullable<int> ToppingId { get; set; }
        public string ItemName { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public string Unit { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetail1 { get; set; }
        public virtual OrderDetail OrderDetail2 { get; set; }
        public virtual Item Item { get; set; }
        public virtual Order Order { get; set; }
    }
}
