//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaiKhatNgocMai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteNew
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public System.DateTime DatePosted { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string UrlTitle { get; set; }
    }
}
